In [3]:
# Create Numpy arrays
import numpy as np

# Converting from a list
#Lets start with a list

my_list1 = [1,2,3,4]

my_array = np.array(my_list1)

#Print or show
my_array


array([1, 2, 3, 4])

In [4]:
print(my_array) # will only print values  separated by space

[1 2 3 4]


In [5]:
# Make another list
my_list2 = [11,22,33,44]

#Make a list of lists
my_lists = [my_list1,my_list2]

#Make multi-dimensional array
my_array2 = np.array(my_lists)

#Show array
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [6]:
#Lets get the size of the array
my_array2.shape

(2, 4)

In [7]:
#Find out the data tyoe of the array
my_array2.dtype

dtype('int32')

In [8]:
#Making special case arrays

#Zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
#Ones
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
# An empty array

np.empty(5)
np.empty((3,4))

array([[1.32888894e-311, 2.71736105e-322, 0.00000000e+000,
        0.00000000e+000],
       [7.56599806e-307, 1.16095484e-028, 2.25566716e+137,
        7.49232601e+247],
       [4.02994783e-144, 2.91237123e+257, 4.71294503e+257,
        1.73431488e-065]])

In [11]:
#Identity array
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
# Using a range

np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
# Create array for operations:
arr1 = np.array([[1,2,3],[8,9,10]])

#Show
arr1


array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [14]:
#Multiplying Arrays
arr1*arr1

array([[  1,   4,   9],
       [ 64,  81, 100]])

In [15]:
#Subtraction
arr1-arr1

array([[0, 0, 0],
       [0, 0, 0]])

In [16]:
#Arithmetic operations with scalars on array
1 / arr1

array([[1.        , 0.5       , 0.33333333],
       [0.125     , 0.11111111, 0.1       ]])

In [17]:
#Exponential operation
arr1 ** 3

array([[   1,    8,   27],
       [ 512,  729, 1000]], dtype=int32)